### ISSUE TITLE
Risk: over-authorization of AWS IoT policy

### ISSUE THREAD

**Issue by P-Verifier** [awsdocs/aws-iot-greengrass-v2-developer-guide#22]
We are a security research team and we recently discovered that there is an over-authorization security issue with this project's IoT policy.
The affected file is as following:

	1. aws-iot-greengrass-v2-developer-guide/doc_source/fleet-provisioning-setup.md

**Comment by FThompsonAWS** [comment]
Thank you for flagging this permissive policy in our documentation. We intentionally use this permissive policy in the docs, so that readers are less likely to run into permission issues when they follow these instructions. The text around this permissive policy explains that the reader can scope the policy down for their use case, and provides a link to other documentation about how to create a more secure IoT policy.
